export const adminMessages = {
  "zh-CN": {
    metaTitle: "管理后台",
    skipToContent: "跳到主要内容",
    dashboard: "管理后台",
    description: "浏览、筛选并管理已上传的文件",
    home: "返回上传页",
    upload: "上传文件",
    uploading: (count: number) => `正在上传 ${count} 个文件…`,
    uploadSuccess: (count: number) => `成功上传 ${count} 个文件`,
    uploadFailure: (count: number) => `${count} 个文件上传失败`,
    uploadTooLarge: "仅支持不超过 20 MB 的文件",
    language: "Switch to English",
    languageShort: "EN",
    logout: "退出登录",
    loginEyebrow: "安全管理入口",
    loginTitle: "登录管理后台",
    loginDescription: "使用部署时配置的管理员账号继续。凭据只会发送到当前站点。",
    username: "用户名",
    usernamePlaceholder: "输入管理员用户名",
    password: "密码",
    passwordPlaceholder: "输入管理员密码",
    signIn: "登录",
    signingIn: "正在验证…",
    loginRequired: "请输入用户名和密码",
    invalidCredentials: "用户名或密码不正确",
    loginFailed: "暂时无法登录，请稍后重试",
    loginSessionNote: "登录状态将在此浏览器中安全保存 8 小时。",
    loaded: "已加载记录",
    image: "图片",
    video: "视频",
    audio: "音频",
    document: "文档",
    allTypes: "全部类型",
    searchLabel: "搜索文件",
    searchPlaceholder: "搜索文件名或 ID",
    filterLabel: "状态筛选",
    allStatuses: "全部状态",
    favorites: "已收藏",
    whitelist: "白名单",
    blacklist: "黑名单",
    adult: "成人内容",
    sortLabel: "排序方式",
    newest: "最新上传",
    nameAscending: "名称升序",
    sizeDescending: "大小降序",
    tableView: "表格视图",
    gridView: "网格视图",
    files: "文件",
    selected: (count: number) => `已选择 ${count} 项`,
    selectFile: (name: string) => `选择 ${name}`,
    selectAll: "选择当前结果",
    clearSelection: "取消选择",
    batchCopy: "复制链接",
    batchWhite: "加入白名单",
    batchBlock: "加入黑名单",
    batchDelete: "删除记录",
    preview: "预览",
    fileName: "文件名",
    kind: "类型",
    size: "大小",
    status: "状态",
    uploadedAt: "上传时间",
    actions: "操作",
    open: "打开文件",
    copyLink: "复制链接",
    rename: "修改显示名称",
    favorite: "收藏",
    unfavorite: "取消收藏",
    addWhite: "加入白名单",
    addBlock: "加入黑名单",
    deleteRecord: "删除记录",
    normal: "普通",
    liked: "收藏",
    unknownType: "文件",
    loading: "正在加载文件…",
    emptyTitle: "没有匹配的文件",
    emptyDescription: "调整搜索或筛选条件，或上传一个新文件。",
    errorTitle: "无法加载管理数据",
    retry: "重试",
    loadMore: "加载更多",
    noMore: "已加载全部记录",
    copied: "链接已复制",
    copyFailed: "复制失败，请手动复制",
    updated: "文件状态已更新",
    deleted: "记录已删除",
    renamed: "显示名称已更新",
    favoriteUpdated: "收藏状态已更新",
    operationFailed: "操作失败，请检查网络连接",
    confirmTitle: "确认操作",
    confirmDelete: (count: number) => `将从管理列表删除 ${count} 条记录。源存储文件不会被删除，但短链接映射会一并移除。`,
    confirmBlock: (count: number) => `将 ${count} 个文件加入黑名单，之后访问会显示屏蔽页面。`,
    confirmWhite: (count: number) => `将 ${count} 个文件加入白名单并允许访问。`,
    cancel: "取消",
    confirm: "确认",
    processing: "处理中…",
    renameTitle: "修改显示名称",
    renameDescription: "只修改后台显示名称，不改变文件 ID 或公开链接。",
    renameLabel: "显示名称",
    renameEmpty: "文件名不能为空",
    save: "保存",
  },
  en: {
    metaTitle: "Admin dashboard",
    skipToContent: "Skip to main content",
    dashboard: "Admin dashboard",
    description: "Browse, filter, and manage uploaded files",
    home: "Back to uploader",
    upload: "Upload files",
    uploading: (count: number) => `Uploading ${count} files…`,
    uploadSuccess: (count: number) => `Uploaded ${count} files`,
    uploadFailure: (count: number) => `${count} uploads failed`,
    uploadTooLarge: "Files must be 20 MB or smaller",
    language: "切换到中文",
    languageShort: "中",
    logout: "Sign out",
    loginEyebrow: "Secure administration",
    loginTitle: "Sign in to the dashboard",
    loginDescription: "Continue with the administrator credentials configured for this deployment. They are sent only to this site.",
    username: "Username",
    usernamePlaceholder: "Enter administrator username",
    password: "Password",
    passwordPlaceholder: "Enter administrator password",
    signIn: "Sign in",
    signingIn: "Verifying…",
    loginRequired: "Enter your username and password",
    invalidCredentials: "The username or password is incorrect",
    loginFailed: "Unable to sign in right now. Try again shortly.",
    loginSessionNote: "Your session is securely retained in this browser for 8 hours.",
    loaded: "Loaded records",
    image: "Images",
    video: "Video",
    audio: "Audio",
    document: "Documents",
    allTypes: "All types",
    searchLabel: "Search files",
    searchPlaceholder: "Search name or ID",
    filterLabel: "Filter by status",
    allStatuses: "All statuses",
    favorites: "Favorites",
    whitelist: "Whitelisted",
    blacklist: "Blocked",
    adult: "Adult content",
    sortLabel: "Sort files",
    newest: "Newest first",
    nameAscending: "Name A–Z",
    sizeDescending: "Largest first",
    tableView: "Table view",
    gridView: "Grid view",
    files: "Files",
    selected: (count: number) => `${count} selected`,
    selectFile: (name: string) => `Select ${name}`,
    selectAll: "Select current results",
    clearSelection: "Clear selection",
    batchCopy: "Copy links",
    batchWhite: "Whitelist",
    batchBlock: "Block",
    batchDelete: "Delete records",
    preview: "Preview",
    fileName: "File name",
    kind: "Type",
    size: "Size",
    status: "Status",
    uploadedAt: "Uploaded",
    actions: "Actions",
    open: "Open file",
    copyLink: "Copy link",
    rename: "Rename display label",
    favorite: "Favorite",
    unfavorite: "Remove favorite",
    addWhite: "Add to whitelist",
    addBlock: "Add to blocklist",
    deleteRecord: "Delete record",
    normal: "Normal",
    liked: "Favorite",
    unknownType: "File",
    loading: "Loading files…",
    emptyTitle: "No matching files",
    emptyDescription: "Change the search or filters, or upload a new file.",
    errorTitle: "Could not load management data",
    retry: "Retry",
    loadMore: "Load more",
    noMore: "All records loaded",
    copied: "Link copied",
    copyFailed: "Could not copy the link",
    updated: "File status updated",
    deleted: "Record deleted",
    renamed: "Display name updated",
    favoriteUpdated: "Favorite updated",
    operationFailed: "The operation failed. Check your connection.",
    confirmTitle: "Confirm action",
    confirmDelete: (count: number) => `Remove ${count} records from the dashboard. Source files remain in storage, but short-link mappings are removed.`,
    confirmBlock: (count: number) => `Add ${count} files to the blocklist. Future visits will show the blocked page.`,
    confirmWhite: (count: number) => `Add ${count} files to the whitelist and allow access.`,
    cancel: "Cancel",
    confirm: "Confirm",
    processing: "Working…",
    renameTitle: "Rename display label",
    renameDescription: "This changes the dashboard label only. The file ID and public URL stay the same.",
    renameLabel: "Display name",
    renameEmpty: "The name cannot be empty",
    save: "Save",
  },
} as const

export type AdminCopy = (typeof adminMessages)[keyof typeof adminMessages]
